name: CI

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:
    release:
        types:
            - created

jobs:
    check_actions:
        name: Check GH Actions
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
            -   uses: reviewdog/action-actionlint@v1
                with:
                    fail_level: 'any'
                    filter_mode: 'nofilter'

    check_composer:
        name: Check composer.json
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
            -   uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: '8.4'
            -   run: composer validate --strict --no-check-lock

    check_code:
        name: Analyse code
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
            -   uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: '8.4'
            -   run: composer update --ansi --no-progress
            -   run: composer lint

    check_readme:
        name: Check README.md
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
            -   uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: '8.4'
            -   run: composer readme .generated-readme.md
            -   run: diff -u README.md .generated-readme.md

    tests:
        name: Build & Test (${{ matrix.osName }}, PHP ${{ matrix.php }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - 'ubuntu-latest'
                osName:
                    - 'Ubuntu'
                php:
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'
                    - '8.3'
                    - '8.4'
                    - '8.5'
                include:
                    -   os: 'macos-15-intel'
                        osName: 'macOS'
                        php: '8.4'
                    -   os: 'windows-latest'
                        osName: 'Windows'
                        php: '8.4'
        steps:
            -   uses: actions/checkout@v6
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    ini-file: "development"
                    coverage: "xdebug"
            -   if: matrix.os == 'macos-15-intel'
                uses: douglascamata/setup-docker-macos-action@v1.1.0
            -   run: composer update --ansi --no-progress
            -   run: composer test -- --coverage-clover=coverage.xml --log-junit junit.xml --testdox
            -   uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: coverage.xml
                    flags: php${{ matrix.php }}
            -   uses: codecov/test-results-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
